version: 2.1

jobs:
  run-api-tests:
    docker:
      # Use official Playwright Docker image (includes all browsers + deps)
      - image: mcr.microsoft.com/playwright:v1.57.0-jammy

    steps:
      - checkout

      # Install node modules
      - run:
          name: Install dependencies
          command: |
            npm ci

      # Install Playwright browsers
      - run:
          name: Install Playwright browsers
          command: |
            npx playwright install --with-deps

      # Run Playwright API tests
      - run:
          name: Run Playwright API tests
          command: |
            npm test

      # Upload reports as artifacts
      - store_artifacts:
          path: playwright-report
      - store_artifacts:
          path: my-allure-results
      - store_test_results:
          path: my-allure-results

workflows:
  version: 2
  run-tests:
    jobs:
      - run-api-tests
